.TH MKASCIIART 1 "15 November 2010"
.SH NAME
mkasciiart \- conveniently convert PGM to ASCII art
.SH SYNOPSIS
.B mkasciiart
.RI [ options... ]
.SH DESCRIPTION
.PP
\fBmkasciiart\fP takes \fInetpbm\fP PGM format on standard
input and converts it to "ASCII art" using
.BR pgmtoasciiart (1)
and other
.BR netpbm (1)
utilities.
.PP
This is a convenience shell script that embodies some
heuristics for quality conversion that the author found
useful.  It also serves as an example of
.BR pgmtoasciiart (1)
usage.
.SH USAGE
.PP
Options are as follows:
.TP
.B "-reverse"
This flag is passed to
.BR pgmtoasciiart (1).
.TP
.BR "-font " tag
This flag is passed to
.BR pgmtoasciiart (1).
.TP
.BI "-width " cols
Produce ASCII art that is \fIcols\fP columns wide. Default
is 132 columns, because the author is \fIold\fP.
.TP
.BI "-yscale " aspect
ASCII characters are a lot taller than they are wide, and
leading makes this more pronounced.  The unitless number
\fIaspect\fP, which defaults to 2.5, is the assumed ratio of
\fIy\fP to \fIx\fP size for characters.
.TP
.BI "-preview " width
Instead of invoking
.BR pgmtoasciiart (1),
produce a PGM of the given pixel \fIwidth\fP
on standard output, showing what the preprocessed
image looks like before final conversion to ASCII.
Mostly useful for debugging.
.SH BUGS
.PP
The \fIyscale\fP should be automatically derived from the
font information.  This is trivial, but communicating the
information to the shell script is less so, so it has not
yet been done.
.PP
Maybe
.B mkasciiart
should take an optional file argument for conversion.
It currently does not, because it is usually used as
part of a pipeline; it did not seem worth the hassle
to add this feature.
.SH AUTHOR
Bart Massey <bart@cs.pdx.edu>
.SH "SEE ALSO"
.BR pgmtoasciiart (1),
.BR asciiarttopgm (1),
.BR asciiarttopbm (1),
.BR netpbm (1),
.BR pgm (5)
