.TH PGMTOASCIIART 1 "14 November 2010"
.SH NAME
pgmtoasciiart \- convert PGM to ASCII art
.SH SYNOPSIS
.B pgmtoasciiart
.RI [ options... ]
.RI [ filename ]
.SH DESCRIPTION
.PP
\fBpgmtoasciiart\fP takes \fInetpbm\fP PGM format and converts
it to "ASCII art" by picking an ASCII character with
appropriate black density for each
pixel of the input image.
.PP
This is a low-level tool.  You may prefer to do this
conversion with the help of
.BR mkasciiart (1).
.SH USAGE
.PP
Options are as follows:
.TP
.B "-reverse"
Reverses the tonal scale, producing an image that is
intended to be displayed as white-on-black.
.TP
.BI "-scale " string
The given \fIstring\fP is treated as a list of ASCII
characters by increasing black density.  The output character
for a given input grey level will be determined by the
position of grey along this list. The space character is
always white, and should be omitted.
.TP
.BI "-font " tag
The given font \fItag\fP is used to determine which built-in scale to
use. Different fonts have different character densities, so this
argument may be useful in dealing with ASCII art that was
produced with a particular font in mind.  Available
font tags as of this writing are "sans", which corresponds
to \fIBitstream Vera Sans Mono\fP, and "typewriter", which
corresponds to \fICourier New\fP.
.SH NOTES
.PP
This is a pretty simplistic implementation, and could be
improved quite a lot.
.PP
The font tones have been measured automatically by rendering
characters. Character patterning is in no way taken into
account in this process.
.SH AUTHOR
Bart Massey <bart@cs.pdx.edu>
.SH "SEE ALSO"
.BR mkasciiart (1),
.BR asciiarttopgm (1),
.BR asciiarttopbm (1),
.BR netpbm (1),
.BR pgm (5)
